title: "Trustworthy Software Ecosystems Lab"
spiel: "TODO"
email: santiagotorres(at)purdue.edu
description: >- 
  TODO
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tse.purdue.wtf/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: torresariass
#github_username: santiagotorres

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
